[profile.default]
src = "src"
out = "out"
solc = "0.8.19"
libs = ["node_modules", "lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".axiom" }]

[rpc_endpoints]
goerli = "${PROVIDER_URI_GOERLI}"
sepolia = "${PROVIDER_URI_SEPOLIA}"

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "multi"
  tab_width = 4
  wrap_comments = false